data_dir:
  kinetics: /data/zubin/videos/kinetics
  davis: /data/zubin/videos/DAVIS/

colorization:
  train:
    epoch: 50
    batch_size: 32
    learning_rate: 0.0001
    direction: 'backward'
    reference_frames_count: 3
    centroids: 'out/centroids/centroids_16k_kinetics_10000samples.npy'
    random: None
  eval:
    batch_size: 32
    reference_frames_count: 3

  # tf.contrib.training.HParams
  hparams:
    data_format: channels_last
    weight_decay: 0.0001
    batch_norm_decay: 0.997
    batch_norm_epsilon: 0.001
